mutation CreateJournalWithEntries(
  $householdId: UUID!,
  $date: Timestamp!,
  $description: String!,
  $accountId1: UUID!,
  $amount1: Float!,
  $prorataFactor1: Float!,
  $accountId2: UUID!,
  $amount2: Float!,
  $prorataFactor2: Float!
) @auth(level: USER) @transaction {
  
  journal_insert(data: {
    householdId: $householdId,
    date: $date,
    description: $description
  })

  entry1: entry_insert(data: {
    journalId_expr: "response.journal_insert.id",
    accountId: $accountId1,
    amount: $amount1,
    prorataFactor: $prorataFactor1,
    ownerUid_expr: "auth.uid"
  })

  entry2: entry_insert(data: {
    journalId_expr: "response.journal_insert.id",
    accountId: $accountId2,
    amount: $amount2,
    prorataFactor: $prorataFactor2,
    ownerUid_expr: "auth.uid"
  })
}

mutation CreateSharedExpenseWithProration(
  $householdId: UUID!,
  $date: Timestamp!,
  $description: String!,
  $totalAmount: Float!,
  $prorataFactor: Float!,
  $payerAccountId: UUID!,
  $user1ExpenseAccountId: UUID!,
  $user2ExpenseAccountId: UUID!,
  $user1Amount: Float!,
  $user2Amount: Float!,
  $payerAmount: Float!
) @auth(level: USER) @transaction {

  journal_insert(data: {
    householdId: $householdId,
    date: $date,
    description: $description
  })

  payerEntry: entry_insert(data: {
    journalId_expr: "response.journal_insert.id",
    accountId: $payerAccountId,
    amount: $payerAmount,
    prorataFactor: $prorataFactor,
    ownerUid_expr: "auth.uid",
    entryType: CREDIT
  })

  user1Entry: entry_insert(data: {
    journalId_expr: "response.journal_insert.id",
    accountId: $user1ExpenseAccountId,
    amount: $user1Amount,
    prorataFactor: $prorataFactor,
    ownerUid_expr: "auth.uid",
    entryType: DEBIT
  })

  user2Entry: entry_insert(data: {
    journalId_expr: "response.journal_insert.id",
    accountId: $user2ExpenseAccountId,
    amount: $user2Amount,
    prorataFactor: $prorataFactor,
    ownerUid_expr: "auth.uid",
    entryType: DEBIT
  })
}

mutation CreateMsiExpense(
  $householdId: UUID!,
  $date: Timestamp!,
  $description: String!,
  $totalAmount: Float!,
  $months: Int!,
  $creditCardAccountId: UUID!,
  $expenseAccountId: UUID!,
  $prorataFactor: Float!,
  $monthlyAmount: Float!
) @auth(level: USER) @transaction {
  journal_insert(data: {
    householdId: $householdId,
    date: $date,
    description: $description,
    isMsi: true
  })
  
  entry_insert(data: {
    journalId_expr: "response.journal_insert.id",
    accountId: $creditCardAccountId,
    amount: $totalAmount,
    prorataFactor: $prorataFactor,
    ownerUid_expr: "auth.uid",
    entryType: CREDIT
  })
}

mutation CreateBudget(
  $householdId: UUID!,
  $categoryName: String!,
  $assignedAmount: Float!,
  $period: Date!,
  $ownerType: OwnerType!
) @auth(level: USER) {
  budget_insert(data: {
    householdId: $householdId,
    categoryName: $categoryName,
    assignedAmount: $assignedAmount,
    period: $period,
    ownerType: $ownerType
  })
}

mutation UpdateBudgetAmount(
  $budgetId: UUID!,
  $assignedAmount: Float!
) @auth(level: USER) {
  budget_update(id: $budgetId, data: {
    assignedAmount: $assignedAmount
  })
}

mutation CreateSavingsProject(
  $householdId: UUID!,
  $name: String!,
  $targetAmount: Float!,
  $priority: Int!
) @auth(level: USER) {
  savingsProject_insert(data: {
    householdId: $householdId,
    name: $name,
    targetAmount: $targetAmount,
    priority: $priority
  })
}

mutation UpdateProjectProgress(
  $projectId: UUID!,
  $amountToAdd: Float!
) @auth(level: USER) {
  savingsProject_update(id: $projectId, data: {
    currentAmount: $amountToAdd
  })
}

mutation CreateExternalAsset(
  $householdId: UUID!,
  $name: String!,
  $estimatedValue: Float!,
  $assetType: String!
) @auth(level: USER) {
  externalAsset_insert(data: {
    householdId: $householdId,
    name: $name,
    estimatedValue: $estimatedValue,
    assetType: $assetType
  })
}

mutation UpdateExternalAsset(
  $assetId: UUID!,
  $estimatedValue: Float!
) @auth(level: USER) {
  externalAsset_update(id: $assetId, data: {
    estimatedValue: $estimatedValue
  })
}

mutation UpsertExchangeRate(
  $currency: String!,
  $rate: Float!,
  $date: Date!
) @auth(level: NO_ACCESS) {
  exchangeRate_upsert(data: {
    currency: $currency,
    rate: $rate,
    date: $date
  })
}
