query GetHouseholdNetBalances($householdId: UUID!) @auth(level: USER) {
  entries(where: { journal: { householdId: { eq: $householdId } }, account: { type: { in: [ASSET, LIABILITY] } } }) {
    ownerUid
    amount
    account {
      id
      type
    }
  }
}
